name: Run Cart Tests

on:
  workflow_dispatch:  # ✅ enables manual trigger from GitHub UI
  push:
    paths:
      - 'tests/cart/**'
  pull_request:
    paths:
      - 'tests/cart/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Cart Tests
        run: npx playwright test tests/cart/
